version: '3.8'

services:
  mysql:
    image: dfc_mysql_image
    container_name: new_dfc_mysql_container_test
    environment:
      MYSQL_ROOT_PASSWORD: withus00
    ports:
      - "3306:3306"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    command: --default-authentication-plugin=mysql_native_password

  spring_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring_dfc_v1
    container_name: springTEST
    volumes:
      - C:\withusDFC\shared:/local/shared/
    ports:
      - "5000:8080"
    command: /bin/bash

  hailo_suite:
    image: hailo_sw_suite_2023-07.1:1
    container_name: hailo_sw_suite_2023-07.1_container_test
    privileged: true
    volumes:
      - C:\withusDFC\shared:/local/shared:rw
      - ./run_dfc.sh:/run_dfc.sh
    command: sh /run_dfc.sh

volumes:
  shared_data: